(() => {
  "use strict";
  const $ = (selector, root = document) => root.querySelector(selector);
  const languageText = {
    en: { skip: "Skip to main content", eyebrow: "A highly unscientific investigation suite", title: "MemeProjects: Your Chaos Tool Suite", tagline: "Explore RU a Cheater?, Persona Evaluator, and chaos modes for every verdict, evaluation, and questionable decision.", language: "Language", choose: "Choose language", mode: "Choose an app mode", modeHelp: "Switch between the cheater detector and the persona evaluator.", cheater: "RU a Cheater?", persona: "Persona Evaluator", chaos: "Choose your chaos level", chaosHelp: "This shared setting controls response intensity, language, and swears across both app modes.", standard: "Standard", spicy: "Spicy", extra: "Extra Spicy", style: "Verdict style", instant: "Instant Verdict", questions: "Question Mode", questionMode: "Question Mode", yes: "Yes, obviously", no: "No, I am pure", reveal: "Reveal my verdict", official: "The official unofficial verdict", who: "Who are we evaluating?", goodBoy: "Good Boy", goodGirl: "Good Girl", badBoy: "Bad Boy", badGirl: "Bad Girl", evalHelp: "The shared chaos level controls intensity and language here too.", evaluate: "Evaluate persona", footerTitle: "Inspect the Crime Scene", footerText: "The intern shipped the vibes, the tests are emotionally unavailable, and the open-source chaos is proudly accepting witnesses.", github: "View the chaos on GitHub", awaiting: "Awaiting evidence...", evaluation: "Awaiting evaluation...", q: "Have you ever replied ‘lol’ while experiencing absolutely no joy?" },
    es: { skip: "Saltar al contenido principal", eyebrow: "Una suite de investigación altamente acientífica", title: "MemeProjects: tu suite del caos", tagline: "Explora RU a Cheater?, el Evaluador de personalidad y modos de caos para cada veredicto.", language: "Idioma", choose: "Elegir idioma", mode: "Elige un modo", modeHelp: "Cambia entre el detector y el evaluador.", cheater: "¿RU un infiel?", persona: "Evaluador de personalidad", chaos: "Elige tu nivel de caos", chaosHelp: "Este ajuste controla la intensidad y el idioma.", standard: "Normal", spicy: "Picante", extra: "Extra picante", style: "Estilo del veredicto", instant: "Veredicto instantáneo", questions: "Modo preguntas", questionMode: "Modo preguntas", yes: "Sí, obviamente", no: "No, soy puro/a", reveal: "Revelar mi veredicto", official: "El veredicto oficial no oficial", who: "¿A quién evaluamos?", goodBoy: "Buen chico", goodGirl: "Buena chica", badBoy: "Chico malo", badGirl: "Mala chica", evalHelp: "El nivel de caos también controla la intensidad.", evaluate: "Evaluar personalidad", footerTitle: "Inspecciona la escena del crimen", footerText: "El becario envió las vibras y el caos open source acepta testigos.", github: "Ver el caos en GitHub", awaiting: "Esperando pruebas...", evaluation: "Esperando evaluación...", q: "¿Alguna vez respondiste «jaja» sin sentir alegría?" },
    fr: { skip: "Aller au contenu principal", eyebrow: "Une suite d’enquête hautement non scientifique", title: "MemeProjects : votre suite du chaos", tagline: "Explorez le détecteur et l’évaluateur de personnalité pour chaque décision douteuse.", language: "Langue", choose: "Choisir la langue", mode: "Choisir un mode", modeHelp: "Passez du détecteur à l’évaluateur.", cheater: "RU un infidèle ?", persona: "Évaluateur de personnalité", chaos: "Choisissez votre niveau de chaos", chaosHelp: "Ce réglage contrôle l’intensité et la langue.", standard: "Classique", spicy: "Piquant", extra: "Extra piquant", style: "Style du verdict", instant: "Verdict instantané", questions: "Mode questions", questionMode: "Mode questions", yes: "Oui, évidemment", no: "Non, je suis pur(e)", reveal: "Révéler mon verdict", official: "Le verdict officiel non officiel", who: "Qui évaluons-nous ?", goodBoy: "Gentil garçon", goodGirl: "Gentille fille", badBoy: "Mauvais garçon", badGirl: "Mauvaise fille", evalHelp: "Le niveau de chaos contrôle aussi l’intensité.", evaluate: "Évaluer la personnalité", footerTitle: "Inspectez la scène du crime", footerText: "Le stagiaire a livré les vibes et le chaos open source accepte les témoins.", github: "Voir le chaos sur GitHub", awaiting: "En attente de preuves…", evaluation: "En attente de l’évaluation…", q: "Avez-vous déjà répondu « lol » sans ressentir de joie ?" }
  };
  const fallbackQuestions = ["Have you ever replied ‘lol’ while experiencing absolutely no joy?", "Did you say ‘I’m five minutes away’ from somewhere much farther away?", "Do you keep a backup excuse for your primary excuse?", "Have you ever opened the fridge hoping new content would load?", "Have you ever said ‘one more episode’ with the confidence of a known liar?"];
  const form = $("#verdict-form"), verdict = $("#verdict"), result = $("#evaluation-result"), panel = $("#question-panel"), question = $("#question-text"), select = $("#language-select");
  let lang = "en", questions = [], remaining = [], currentQuestion = "";
  const pick = list => list[Math.floor(Math.random() * list.length)];
  function refillQuestions() { remaining = questions.filter(item => item !== currentQuestion); if (!remaining.length) remaining = questions.slice(); }
  function nextQuestion() { if (!remaining.length) refillQuestions(); currentQuestion = remaining.splice(Math.floor(Math.random() * remaining.length), 1)[0]; question.textContent = currentQuestion; }
  function applyLanguage(value) { lang = languageText[value] ? value : "en"; const text = languageText[lang]; document.documentElement.lang = lang; try { localStorage.setItem("memeprojects-language", lang); } catch (_) {} document.querySelectorAll("[data-i18n]").forEach(el => { if (text[el.dataset.i18n]) el.textContent = text[el.dataset.i18n]; }); select.value = lang; question.textContent = currentQuestion || text.q; verdict.textContent = text.awaiting; result.textContent = text.evaluation; update(); }
  function update() { const questionMode = $("input[name=pace]:checked", form)?.value === "questions"; panel.hidden = !questionMode; panel.setAttribute("aria-hidden", String(!questionMode)); $("#verdict-button").textContent = questionMode ? languageText[lang].questions : languageText[lang].reveal; if (questionMode && !currentQuestion) nextQuestion(); }
  function roast(answer) { const mode = $("input[name=mode]:checked", form)?.value || "standard"; const bank = window.roastData || {}; const pool = [...(bank[mode] || []), ...(bank[answer === "yes" ? "answerFollowUps" : "witnessStatements"]?.[answer] || [])]; const base = pool.length ? pick(pool) : (answer === "yes" ? "The witness confirms it: bold, chaotic, and inadmissible." : "The witness denies everything with suspicious confidence."); return `${currentQuestion ? `Regarding “${currentQuestion}”: ` : ""}${base}`; }
  function answer(choice) { verdict.textContent = roast(choice); verdict.focus(); nextQuestion(); }
  async function loadRoasts() { try { const response = await fetch("roasts.json"); if (response.ok) window.roastData = await response.json(); } catch (_) {} }
  select.onchange = () => applyLanguage(select.value);
  form.onsubmit = event => { event.preventDefault(); verdict.textContent = roast("no"); verdict.focus(); if ($("input[name=pace]:checked", form)?.value === "questions") nextQuestion(); };
  $("#yes-button").onclick = () => answer("yes"); $("#no-button").onclick = () => answer("no");
  $("#evaluate-button").onclick = () => { result.textContent = roast($("input[name=evaluator-title]:checked")?.value || "good-boy"); result.focus(); };
  document.querySelectorAll('input[name="pace"]').forEach(input => input.onchange = update);
  document.querySelectorAll('input[name="primary-mode"]').forEach(input => input.onchange = () => { const evaluator = input.value === "evaluator"; $("#cheater-panel").hidden = evaluator; $("#evaluator-panel").hidden = !evaluator; });
  document.addEventListener("DOMContentLoaded", async () => { await loadRoasts(); let saved = ""; try { saved = localStorage.getItem("memeprojects-language") || ""; } catch (_) {} const browserLanguage = navigator.languages?.[0] || navigator.language || "en"; const detected = (saved || browserLanguage).toLowerCase().split(/[-_]/)[0]; questions = window.roastData?.questions?.length ? window.roastData.questions : fallbackQuestions; remaining = questions.slice(); applyLanguage(languageText[detected] ? detected : "en"); });
})();